<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12.0</LangVersion>
    <AssemblyName>sra</AssemblyName>
    <RootNamespace>ScheduleRisk.Cli</RootNamespace>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <TieredPGO>true</TieredPGO>
    <Version>0.4.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScheduleRisk.Core\ScheduleRisk.Core.csproj" />
  </ItemGroup>

</Project>
